trigger: none

resources:
  pipelines:
  - pipeline: build
    project: UnifiedEdgeScenarios
    source: Build ues-app
    trigger:
      branches: 
        include:
        - master
        - BuildReleasePipeline


pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  jobs:
  - job: Download 
    steps:
    - checkout: none
    - download: none

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: 'e9d7d516-43c2-413f-b83b-f320777504c6'
        definition: '14'
        buildVersionToDownload: 'latest'
        artifactName: 'ues_app'
        targetPath: '$(Pipeline.Workspace)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Pipeline.Workspace)'
        Contents: 'people-detection-app.zip'
        TargetFolder: '/home/vsts/work/1/s'
       
    - task: Bash@3
      env:
          SP_APP_PWD: $(SP_APP_PWD)
      inputs:
        targetType: 'inline'
        script: |
             # Write your commands here
             WEBAPP_DEPLOYMENT_ZIP="people-detection-app.zip"
             echo "Attempting login with Service Principal account"
             az login --service-principal --username "$SP_APP_ID" --password "$SP_APP_PWD" --tenant "$TENANT_ID" --output "none"
             echo "Login successful"
             
             IOTHUB_CONNECTION_STRING="$(az iot hub show-connection-string --name "$IOTHUB_NAME" --query "connectionString" --output tsv)"
             
             az webapp config connection-string set --connection-string-type Custom --name "$WEBAPP_NAME" --resource-group "$RESOURCE_GROUP" --settings "EventHub=$IOTHUB_CONNECTION_STRING" --output "none"
             # Turn on web sockets
             az webapp config set --resource-group "$RESOURCE_GROUP" --name "$WEBAPP_NAME" --web-sockets-enabled true --output "none"

             echo "Web App settings have been configured"

             echo "Deploying Web App using \"$WEBAPP_DEPLOYMENT_ZIP\" zip file"
             # Step to deploy the app to azure
             az webapp deployment source config-zip --resource-group "$RESOURCE_GROUP" --name "$WEBAPP_NAME" --src "$WEBAPP_DEPLOYMENT_ZIP" --output "none"
             echo "Deployment is complete"

- stage: Publish
  jobs:
  - deployment: 'Publish'
    displayName: 'Publish_Artifacts'
    environment: 'ApproveFrontEndRelease'
    strategy:
      runOnce:
        deploy:
          steps: 
          - checkout: none
          - download: none

          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: 'e9d7d516-43c2-413f-b83b-f320777504c6'
              definition: '14'
              buildVersionToDownload: 'latest'
              artifactName: 'ues_app'
              targetPath: '$(Pipeline.Workspace)'


          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Pipeline.Workspace)/people-detection-app.zip'
              artifact: 'ues_app'
              publishLocation: 'pipeline'